### ISSUE TITLE
Add Ban button on profile pages

### ISSUE THREAD

**Issue by CyrusV5** [slickage/beta.bitcointalk.org#39]

**Comment by taesup** [comment]
Would this button be a permanent ban or should it bring up the banning modal found on the moderation page? This way you can set if they are permanently banned, temporarily banned, or banned from a board.

**Comment by CyrusV5** [comment]
Ideally it would open the banning modal, with the username already set in the user field and the mod only needing to set the boards and duration.

**Comment by akinsey** [comment]
This commit adds this feature:

https://github.com/epochtalk/ept-frontend/commit/000111f766b366fb85896adb429f83335c7d2fdd
