### ISSUE TITLE
Show number of Moderation Notes on profile pages

### ISSUE THREAD

**Issue by CyrusV5** [slickage/beta.bitcointalk.org#40]
Most profiles probably won't have any notes but it would be nice to have a visual hint that a profile has them.
a. saves us a click;
b. we'll pay more attention when we do see them on profiles.

**Comment by taesup** [comment]
So it might be hard to show an actual number because we aren't keeping track of the number of notes right now. Would be enough to have an icon that just indicates that there are notes?

**Comment by taesup** [comment]
A preliminary version of this is now in commit: https://github.com/epochtalk/ept-frontend/commit/5da9cce4c141efbee1858fc8ad96f4e783e20a02

**Comment by CyrusV5** [comment]
An icon to let us know that there's something there is perfect. Thanks for adding it!
